package view;

public enum ActionId {
	GUI_READY,
	EXIT,
	LOGIN_BUTTON,
	LOGIN_SUBMIT,
	LOGOUT_BUTTON,
	REGISTER_BUTTON,
	REGISTER_SUBMIT,
	ADD_ROOM_BUTTON,
	ADD_ROOM_SUBMIT,
	BOOK_ROOM_BUTTON,
	BOOK_ROOM_SUBMIT,
	CONFIRM_BOOKING_BUTTON,
	CONFIRM_BOOKING_SUBMIT,
	CREATE_ADMIN_BUTTON,
	CREATE_ADMIN_SUBMIT,
	DELETE_ADMIN_BUTTON,
	DELETE_ADMIN_SUBMIT,
}